Relax --delete requirements through a new option
openafs-contrib/cellcc pull request #5
Opened 2018-03-01 00:50 UTC by marciobarbosa

The original cellcc start-sync --delete flag is used to delete the
specified volume in all destination cells. This option only works if
the volume in question was already removed from the source cell.
Unfortunately, this is not always desirable.

This commit introduces a new flag called --forcedelete. This option
deletes the specified volume in all destination cells even if this
volume still exists in the source cell.

2018-03-06 22:34 UTC, adeason requested changes
The behavior of CELLCC_FILTER_OPERATION seems to disagree with the documentation, in this commit. I'm not sure which way I prefer... I'm learning towards how the code does it (no separate 'forcedelete' operation; the --forcedelete flag just causes the 'delete' operation), but I'm not sure. Either way is okay with me, but of course the documentation and code need to be in agreement.

Also, could you change the name of the command-line flag to "--force-delete"? I know --forcedelete was mentioned by the person requesting this, but I don't think they are very particular about the exact spelling, and having a separator in the words makes it a lot easier to read. (variable names and stuff don't need to change, unless you want them to)

2018-03-06 22:34 UTC, adeason commented on doc/pod1/cellcc_config.pod
> +=item C<forcedelete>
This doc change doesn't seem to agree with... (see below)

2018-03-06 22:34 UTC, adeason commented on lib/AFS/CellCC.pm
> +    if ($opts->{delete} || $opts->{forcedelete}) {
(from above)... this code change. We still set CELLCC_FILTER_OPERATION to 'delete', whether we are deleting or force-deleting

2018-03-09 21:51 UTC, marciobarbosa commented
Branch updated.

Thank you!

2018-03-09 22:02 UTC, adeason approved these changes

2018-03-09 22:02 UTC, merged